### ISSUE TITLE
Send push to one devices

### ISSUE THREAD

**Issue by Gadgetroch** [gotify/server#388] opened 2021-02-06 19:21 UTC
**You are setting up gotify in**
- [X] Docker
- [X] Linux native platform
- [ ] Windows native platform

Good morning,

How can send a message to one device ?
I'm trying to use message with token device, but i get that i'm not authorize...

Thank's

**Comment by jmattheis** [comment] 2021-02-06 19:39
Duplicate of feature request -> https://github.com/gotify/server/issues/186

**Closed by jmattheis** 2021-02-06 19:39 UTC
Labels: question
