### ISSUE TITLE
fix --openssl-legacy-provider

### ISSUE THREAD

**Issue by icetech233** [gotify/server#694] opened 2024-10-07 13:55 UTC
--openssl-legacy-provider

**Comment by najtin** [comment] 2024-10-07 14:34
Based on the information in #693 and the proposed solution to a very similar problem on [stackoverflow](https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e) this seems to be a duplicate of #693.

**Comment by eternal-flame-AD** [comment] 2024-10-07 15:07
I tried, it's not trivial to get around this and I think there is low practical value to practically rewrite the UI that don't fix any functionality but just to get around an well accepted workaround.

**Comment by jmattheis** [comment] 2024-10-07 16:09
Dupe -> #574

**Closed by jmattheis** 2024-10-07 16:09 UTC
Labels: a:feature
