### ISSUE TITLE
Sidebar doesnt scroll with page

### ISSUE THREAD

**Issue by rtm516** [gotify/server#406] opened 2021-04-12 13:36 UTC
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

![image](https://user-images.githubusercontent.com/5401186/114402938-3c12ca80-9b9c-11eb-93eb-ab2eb9f8d84c.png)
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

Using NginxProxyManager
![image](https://user-images.githubusercontent.com/5401186/114403048-58166c00-9b9c-11eb-8c95-779132708549.png)
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Load the web GUI and scroll down

**What did you expect to see?**
The sidebar should scroll with the page

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
The sidebar stays fixed at the top of the page producing issues like this
![image](https://user-images.githubusercontent.com/5401186/114402773-108fe000-9b9c-11eb-8bde-2bb50ce3f948.png)

**Comment by jmattheis** [comment] 2021-04-12 16:14
I'd say this is by design and no bug.

**Comment by rtm516** [comment] 2021-04-13 09:36
It looks bad, at least have the sidebar color extend to the bottom of the page and not just the screen height.

**Comment by jmattheis** [comment] 2021-04-14 19:40
This should be fixed with https://github.com/gotify/server/commit/1cbd273974426209e6487a0091f2b5834c122afd

**Closed** 2021-06-27 12:09 UTC
Labels: a:bug
